name: popdot
description: Le jukebox qui dépote

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # IconPicker
  flutter_iconpicker: ^3.1.4+1

  # FilePicker
  file_picker: ^4.5.1

  # Firebase
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.16
  firebase_storage: ^10.2.16

  # Hive
  hive: ^2.1.0
  path_provider: ^2.0.9
  hive_flutter: ^1.1.0

  #FlutterToast
  fluttertoast: ^8.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

  # Audio Player
  just_audio: ^0.9.20

flutter:
  assets:
    - assets/images/

  uses-material-design: true