name: popdot
description: Le jukebox qui dépote 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # FilePicker
  file_picker: ^4.5.1

  # Firebase
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.16
  firebase_storage: ^10.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true